version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: jeevo-postgres
    environment:
      POSTGRES_DB: jeevo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
<<<<<<< HEAD
      - "5433:5432"   # âœ… changed from 5432 to 5433
=======
      - "5432:5432"
>>>>>>> origin/jp2
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: jeevo-redis
    ports:
<<<<<<< HEAD
      - "6380:6379"
=======
      - "6379:6379"
>>>>>>> origin/jp2

  backend:
    build: .
    container_name: jeevo-backend
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: jeevo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"

volumes:
  pgdata:
